---
- name: Download kepler archive from GH releases (localhost)
  ansible.builtin.get_url:
    url: https://github.com/sustainable-computing-io/kepler/releases/latest/download/kepler.rpm.tar.gz
    dest: "{{ kepler_tgz_loc }}"
  delegate_to: localhost
  run_once: true

- name: Create dir for extraction (localhost)
  ansible.builtin.file:
    path: "{{ kepler_extracted_loc }}"
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Extract archive (localhost)
  ansible.builtin.unarchive:
    src: "{{ kepler_tgz_loc }}"
    dest: "{{ kepler_extracted_loc }}"
    list_files: true
    extra_opts:
      - "--strip-components=1"
  delegate_to: localhost
  run_once: true

- name: Find RPM in extracted contents (localhost)
  ansible.builtin.find:
    paths: "{{ kepler_extracted_loc }}"
    patterns: "kepler-*.x86_64.rpm"
    recurse: true
  register: local_rpm_loc
  delegate_to: localhost

- name: Move over RPM
  ansible.builtin.copy:
    src: "{{ local_rpm_loc['files'][0]['path'] }}"
    dest: "/tmp"
  register: remote_rpm_loc

- name: Install RPM
  ansible.builtin.dnf:
    name: "{{ remote_rpm_loc['dest'] }}"
    state: present
    # FIXME
    # for some reason, the file can be installed without issues manually
    # but when doing the exact same via ansible the following error occurs:
    # "Failed to validate GPG signature for kepler-0.7.2-0.7.2.x86_64: Package kepler-0.7.2-0.7.2.x86_64.rpm is not signed"
    disable_gpg_check: true
